#!/usr/bin/env python
# -*- coding: utf-8 -*-


def tags(tag):
    def wrapper_func(func):
        def wrapper(self):
            return "<{0}>{1}</{0}>".format(tag, func(self))
        return wrapper
    return wrapper_func


class Person(object):

    """docstring for Person"""

    def __init__(self, name, id):
        super(Person, self).__init__()
        self.name = name
        self.id = id

    @tags("Strong")
    def outputp(self):
        return "name:{0}, id:{1}".format(self.name, self.id)

    def printP(self):
        print self.outputp()

p = Person("Peter", 3)
p.printP()

# print p.printP.__main__
print dir(p.printP)
