# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
